export function generateMarkdownReport(report) {
    const lines = [];
    lines.push(`# OpenGEO Audit Report`);
    lines.push("");
    lines.push(`**Target:** ${report.metadata.target_url}`);
    lines.push(`**Date:** ${report.metadata.finished_at}`);
    lines.push(`**Pages crawled:** ${report.metadata.pages_crawled}`);
    lines.push(`**Rules evaluated:** ${report.metadata.rules_evaluated}`);
    lines.push(`**Tool version:** ${report.metadata.tool_version}`);
    lines.push("");
    const critical = report.findings.filter((f) => f.severity === "critical");
    const high = report.findings.filter((f) => f.severity === "high");
    const medium = report.findings.filter((f) => f.severity === "medium");
    const low = report.findings.filter((f) => f.severity === "low");
    lines.push(`## Summary`);
    lines.push("");
    lines.push(`| Severity | Count |`);
    lines.push(`|----------|-------|`);
    lines.push(`| Critical | ${critical.length} |`);
    lines.push(`| High | ${high.length} |`);
    lines.push(`| Medium | ${medium.length} |`);
    lines.push(`| Low | ${low.length} |`);
    lines.push("");
    if (report.findings.length === 0) {
        lines.push(`## Findings`);
        lines.push("");
        lines.push(`No issues detected. This does not guarantee AI-search readiness — it means no rule violations were found within the crawled scope.`);
        return lines.join("\n");
    }
    const grouped = groupByCategory(report.findings);
    for (const [category, findings] of Object.entries(grouped)) {
        lines.push(`## ${formatCategory(category)}`);
        lines.push("");
        for (const finding of findings) {
            lines.push(formatFindingMd(finding));
        }
    }
    lines.push("---");
    lines.push("");
    lines.push(`*Generated by OpenGEO v${report.metadata.tool_version}. This report provides evidence-backed findings, not guarantees. See [methodology](https://github.com/DjimIT/opengeo/docs/methodology) for scoring details.*`);
    return lines.join("\n");
}
function formatFindingMd(finding) {
    const lines = [];
    lines.push(`### \`${finding.id}\` — ${finding.title}`);
    lines.push("");
    lines.push(`**Severity:** ${finding.severity} | **Confidence:** ${finding.confidence} | **Category:** ${finding.category}`);
    lines.push("");
    lines.push(`**Impact:** Search: ${finding.impact.search} | AI Retrieval: ${finding.impact.ai_retrieval} | Model Training: ${finding.impact.model_training} | UX: ${finding.impact.user_experience}`);
    lines.push("");
    lines.push(`**Evidence:**`);
    lines.push(`- URL: ${finding.evidence.url}`);
    if (finding.evidence.snippet)
        lines.push(`- ${finding.evidence.snippet}`);
    if (finding.evidence.lines) {
        for (const line of finding.evidence.lines) {
            lines.push(`  - \`${line}\``);
        }
    }
    lines.push("");
    lines.push(`**Recommendation:** ${finding.recommendation.action} (${finding.recommendation.effort} effort)`);
    lines.push(`> ${finding.recommendation.rationale}`);
    lines.push("");
    if (finding.patch) {
        lines.push(`**Suggested Patch:**`);
        lines.push("```diff");
        lines.push(finding.patch.content);
        lines.push("```");
        lines.push("");
    }
    lines.push(`**Sources:**`);
    for (const source of finding.sources) {
        const urlPart = source.url ? ` (${source.url})` : "";
        lines.push(`- ${source.vendor} [${source.type}]${urlPart}`);
    }
    lines.push("");
    lines.push(`**Rule:** ${finding.rule_metadata.status} | Evidence level: ${finding.rule_metadata.evidence_level} | Last reviewed: ${finding.rule_metadata.last_reviewed} | Maintainer: ${finding.rule_metadata.maintainer}`);
    lines.push("");
    return lines.join("\n");
}
function groupByCategory(findings) {
    const grouped = {};
    for (const f of findings) {
        if (!grouped[f.category])
            grouped[f.category] = [];
        grouped[f.category].push(f);
    }
    return grouped;
}
function formatCategory(category) {
    return category
        .split("-")
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(" ");
}
//# sourceMappingURL=markdown.js.map